In [11]:
n = 250000000
print(f'({n}^3+3*{n}^2+2*{n})/6')
print(f'({n}^3-{n})/6')
print(f'({n}^2)-{n})/2')
print(f'{n}*log({n})-n+1')

(250000000^3+3*250000000^2+2*250000000)/6
(250000000^3-250000000)/6
(250000000^2)-250000000)/2
250000000*log(250000000)-n+1


In [1]:
import numpy as np

mat = np.array([[0, 1, 1, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 1, 1], [0, 0, 0, 0, 1], [0, 1, 0, 1, 0]])

mat**1000

array([[0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0]])

In [2]:
row_sums = np.sum(mat == 1, axis=1)
mat_new = np.where(mat == 1, 1/row_sums[:, np.newaxis], mat)
mat_new


array([[0.        , 0.5       , 0.5       , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.5       , 0.        , 0.5       , 0.        ]])

In [7]:
mat_new**1000

array([[0.00000000e+000, 9.33263619e-302, 9.33263619e-302,
        0.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000],
       [0.00000000e+000, 9.33263619e-302, 0.00000000e+000,
        9.33263619e-302, 0.00000000e+000]])

In [15]:
len([x for x in range(1, 150+1) if x % 4 == 0 or x % 9 == 0])/150

0.32666666666666666

In [13]:
len([x for x in range(1, 150+1) if x % 4 == 0 and x % 9 == 0])

4

In [14]:
(16+37-4)/150

0.32666666666666666

In [22]:
%time
from sympy import Poly

def calc_coeff_xk(n, k):
    poly = Poly(x + x**2 + x**3 + x**4 + x**5 + x**6)
    poly_n = poly**n
    coeff = poly_n.coeff_monomial(x**k)
    probability = coeff / 6**n
    return probability
calc_coeff_xk(15, 62)

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 1.91 µs


1144106375/52242776064

In [34]:
%time
import math

def calc_coeff_directly(n, k):
    total_coeff = 0
    max_i = k // 6
    max_j = k
    for j in range(max_j+1):
        for i in range(max_i+1):
            if n + 6*i + j == k:
                total_coeff += ((-1)**i) * math.comb(n, i) * math.comb(n + j - 1, j)
    probability = total_coeff / 6**n
    return probability
calc_coeff_directly(15, 62)

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 2.86 µs


0.02189980053124307

In [25]:
1144106375/52242776064

0.02189980053124307